# Variables
CXX = g++
CXXFLAGS = -std=c++98 -Wall -Wextra -Werror
SRC = main.cpp Sample1.class.cpp Sample2.class.cpp

# Targets
all: output

output:
	$(CXX) $(CXXFLAGS) $(SRC) -o output

clean:
	rm -f output
